server {
    listen 80;
    root /var/www/html;
    index index.html index.php;
    server_tokens off;

    charset utf-8;

    location /_astro/ {
        expires 365d;
        add_header Cache-Control "public, immutable";
    }

    location /images/ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /uploads/ {
        expires 30d;
        add_header Cache-Control "public, immutable";

        location ~ \.php$ {
            deny all;
            return 403;
        }
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_param PHP_VALUE "display_errors=0";
    }

    location / {
        try_files $uri $uri/ $uri/index.html $uri/index.php =404;
    }

    location ~ /\. {
        deny all;
        return 404;
    }

    location ~ (\.env|\.git|composer\.|package-lock\.|ip3\.zip) {
        deny all;
        return 404;
    }
}
